services:
  booking_back:
    container_name: booking_back
    build:
      context: .
    ports:
      # - 7777:8000
    networks:
      - my_network
    env_file:
      - .env

  booking_celery_worker:
    container_name: booking_celery_worker
    build:
      context: .
    networks:
      - my_network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

  booking_celery_beat:
    container_name: booking_celery_beat
    build:
      context: .
    networks:
      - my_network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  my_network:
    external: true