"""create users

Revision ID: a1654104d975
Revises: 7ee8acac53cb
Create Date: 2025-06-06 17:40:33.998621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1654104d975"
down_revision: Union[str, None] = "7ee8acac53cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")  # type: ignore
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
